title: Marie Tano
url: "https://mariemmanue.github.io"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
footer_url: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 # - name: "Research"
 #   link: "research"
 - name: "CV"
   link: "/resume_tano.pdf"

social:
  email:    "mailto:mtano@stanford.edu"
  linkedin: "https://www.linkedin.com/in/marie-emmanue/"
  scholar:  "https://scholar.google.com/citations?hl=en&user=2MKh4nYAAAAJ"
  github:   "https://github.com/mariemmanue"
